version: "3.5"
services:
  go-backend-user:
    platform: linux/amd64
    container_name: go-backend-user
    build: 
      context: ./.dockers/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_backend_user
    ports:
      - "3321:3306"
    volumes:
      - ./.dockers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql